version: '3'

services:  
  prisma:
    image: prismagraphql/prisma:1.34
    container_name: prisma
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: 79dea521ddb251eb9700d849fa5fbf94
        port: 4466
        databases:
          default:
            connector: mongo
            uri: 'mongodb://root:root@mongo/?authSource=admin'
    depends_on:
      - mongo
    networks:
      - web_default

  mongo:
    image: 'mongo:latest'
    container_name: mongo
    ports:
      - '27017:27017'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - './data/mongo/db:/data/db'
    networks:
      - web_default

networks:
  web_default:
    bridge: true

volumes:
  mongodb_data:
    driver: local
  initMongo:
    driver: local